export enum AgencyPermission {
  AGENCY_VIEW = 'AGENCY_VIEW',
  AGENCY_MANAGE = 'AGENCY_MANAGE',
  TEAM_VIEW = 'TEAM_VIEW',
  TEAM_MANAGE = 'TEAM_MANAGE',
  ROLES_MANAGE = 'ROLES_MANAGE',
  PROPERTIES_VIEW = 'PROPERTIES_VIEW',
  PROPERTIES_MANAGE = 'PROPERTIES_MANAGE',
  LEADS_VIEW = 'LEADS_VIEW',
  LEADS_MANAGE = 'LEADS_MANAGE',
  MESSAGES_VIEW = 'MESSAGES_VIEW',
  MESSAGES_MANAGE = 'MESSAGES_MANAGE',
}
